---
name: Sync repo files
on:
  schedule:
    - cron: '44 17 * * *'
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'prometheus'
    container:
      image: quay.io/prometheus/golang-builder
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PROMBOT_GITHUB_TOKEN }}
